### ISSUE TITLE
When scrolling down the list of replays the entire program crashes

### ISSUE THREAD

**Issue by BryanGreenaway** [TcT2k/RLReplayManager#1]
I selected upload log file when that popped up, it happens every time. I can maximize the window and then pull down the replay list so it is basically the whole screen top to bottom, but once I start scrolling it crashes. Navigating down using the arrows causes it to crash as well.

**Comment by BryanGreenaway** [comment]
Found out the problem, I think one of my .replay files was bad corrupted. I removed it from the Demo directory and the program doesn't crash. Maybe some check could be put in to make sure the .replay file is valid before trying to parse out the data?

I tried attaching the "bad" .replay file, but github doesn't allow .replay, I changed to .txt but I don't have permission to upload it. So I dropped it on Mega here
https://mega.nz/#!9p8kDRQJ!io8Sf2dD1VPHE6naWOrIqO_a-wARvggD69A7mDSRLtM

**Comment by Faskis** [comment]
Same issue, corrupt .replay file. I've uploaded the corrupted file that I had: http://puu.sh/l1FnL/9a80481b2b.replay

From the event logs (if it's of any help):

> Faulting application name: RLReplayManager.exe, version: 0.3.0.0, time stamp: 0x561d58e7
> Faulting module name: RLReplayManager.exe, version: 0.3.0.0, time stamp: 0x561d58e7
> Exception code: 0xc000041d
> Fault offset: 0x0001295e
> Faulting process id: 0x1acc
> Faulting application start time: 0x01d112110218954e
> Faulting application path: Z:\Downloads\RLReplayManager-0.3.0-win32\RLReplayManager-0.3.0-win32\RLReplayManager.exe
> Faulting module path: Z:\Downloads\RLReplayManager-0.3.0-win32\RLReplayManager-0.3.0-win32\RLReplayManager.exe
> Report Id: cd664984-86cc-47ea-b423-3153f33a9668
> Faulting package full name: 
> Faulting package-relative application ID:
