### ISSUE TITLE
How does automatic replay upload work?

### ISSUE THREAD

**Issue by axelson** [TcT2k/RLReplayManager#6]
It doesn't seem to be uploading the replays automatically. Is there something I need to do for it?

**Comment by TcT2k** [comment]
There was an option in your account settings of rocketleaguereplays.com before the Stream SIgn In. Currently that option is not available. @danielsamuels Will this get added back?

**Comment by danielsamuels** [comment]
Instructions are available on [this page](https://www.rocketleaguereplays.com/replays/upload/).

**Comment by TcT2k** [comment]
Sorry didn't look close enough for the new location :)
